### ISSUE TITLE
Underrail Expansion Issue

### ISSUE THREAD

**Issue by Stah01** [LeonBlade/xnbcli#18]
Hi,

I wanted to edit Underrail sprites and redo some of them.  The base game seems to unpack fine and this tool works great to unpack and repack.    The expedition expansion seems to cause an error though and I was hoping you could take a look.  Weirdly it isnt every new expansion file so I found 4 that had this issue.  

[INFO] Reading file "packed\1p33.xnb" ...
[INFO] XNB file validated successfully!
[ERROR] Filename: packed\1p33.xnb
XnbError: Decode table did not reach table mask.
    at Lzx.decodeTable (C:\snapshot\xnbcli\app\Presser\Lzx.js:0:0)
    at Lzx.decompress (C:\snapshot\xnbcli\app\Presser\Lzx.js:0:0)
    at Function.decompress (C:\snapshot\xnbcli\app\Presser\index.js:0:0)
    at Xnb.load (C:\snapshot\xnbcli\app\Xnb\index.js:0:0)
    at processUnpack (C:\snapshot\xnbcli\xnbcli.js:0:0)
    at Walker.walker.on (C:\snapshot\xnbcli\xnbcli.js:0:0)
    at Walker.emit (events.js:182:13)
    at Object.emitSingleEvents [as emitNodeType] (C:\snapshot\xnbcli\node_modules\walk\lib\node-type-emitter.js:58:13)
    at Walker._wLstatHandler (C:\snapshot\xnbcli\node_modules\walk\lib\walk.js:88:19)
    at C:\snapshot\xnbcli\node_modules\walk\lib\walk.js:106:12

Here is a link to the xnb files

http://www.mediafire.com/file/pu9y9wfkxa3y5v3/Underrrail_Error.7z/file

**Comment by LeonBlade** [comment]
Thanks for this report.  I’ll look into it when I have some time.

**Comment by LeonBlade** [comment]
Do other XNB files from this game work or do they all fail like this?   You
are correct, it was mainly created for SDV, but I will spend some time
looking into this regardless.  Thanks!

**Comment by LeonBlade** [comment]
Going to close this as it's pretty old at this point.  The rewrite I'm doing may help fix this issue, not sure yet.  If this is still something you care about, please feel free to comment or open a new issue when the time comes.  

Thank you.
