### ISSUE TITLE
Unable to unpack Movies.xnb in /Content/Data

### ISSUE THREAD

**Issue by KonaKona7** [LeonBlade/xnbcli#31]
[ERROR] Filename: packed\Movies.xnb
XnbError: Non-implemented type found, cannot resolve type "StardewValley.GameData.Movies.MovieData", "StardewValley.GameData.Movies.MovieData, StardewValley.GameData, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".
    at simplifyType (C:\snapshot\xnbcli\app\Xnb\TypeReader.js:0:0)
    at Array.map (<anonymous>)
    at simplifyType (C:\snapshot\xnbcli\app\Xnb\TypeReader.js:0:0)
    at Xnb.load (C:\snapshot\xnbcli\app\Xnb\index.js:0:0)
    at processUnpack (C:\snapshot\xnbcli\xnbcli.js:0:0)
    at Walker.walker.on (C:\snapshot\xnbcli\xnbcli.js:0:0)
    at Walker.emit (events.js:198:13)
    at Object.emitSingleEvents [as emitNodeType] (C:\snapshot\xnbcli\node_modules\walk\lib\node-type-emitter.js:58:13)
    at Walker._wLstatHandler (C:\snapshot\xnbcli\node_modules\walk\lib\walk.js:88:19)
    at C:\snapshot\xnbcli\node_modules\walk\lib\walk.js:106:12

**Comment by LeonBlade** [comment]
Unfortunately, xnbcli doesn't support this right now.

**Comment by Pathoschild** [comment]
This duplicates #13, so we can probably close this one.
