### ISSUE TITLE
Support for Carrion?

### ISSUE THREAD

**Issue by The-Almighty-Zugs** [LeonBlade/xnbcli#32]
Trying to figure out how to fix this error. 
![image](https://user-images.githubusercontent.com/68722428/88358935-deed9500-cd3e-11ea-8475-fc5f2d49a3f6.png)

**Comment by LeonBlade** [comment]
Reflection Reader is not currently supported I'm afraid. It is in the works, but I'm not sure when I'll be able to get around to it.

**Comment by dcbishop** [comment]
The game also uses some custom types.

```
[INFO] Reading file "packed\LevelTextures.xnb" ...
[WARN] Invalid target platform "d" found.
[INFO] XNB file validated successfully!
[ERROR] Filename: packed\LevelTextures.xnb
XnbError: Non-implemented type found, cannot resolve type "Monster.ContentReaders.GeneratorTextureFileReader", "Monster.ContentReaders.GeneratorTextureFileReader, SharedTypes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".
    at simplifyType (C:\snapshot\xnbcli\app\Xnb\TypeReader.js:0:0)
    at Xnb.load (C:\snapshot\xnbcli\app\Xnb\index.js:0:0)
    at processUnpack (C:\snapshot\xnbcli\xnbcli.js:0:0)
    at Walker.walker.on (C:\snapshot\xnbcli\xnbcli.js:0:0)
    at Walker.emit (events.js:198:13)
    at Object.emitSingleEvents [as emitNodeType] (C:\snapshot\xnbcli\node_modules\walk\lib\node-type-emitter.js:58:13)
    at Walker._wLstatHandler (C:\snapshot\xnbcli\node_modules\walk\lib\walk.js:88:19)
    at C:\snapshot\xnbcli\node_modules\walk\lib\walk.js:106:12
    at FSReqWrap.oncomplete (fs.js:154:5)

Success 0
Fail 1
```

**Comment by LeonBlade** [comment]
Not supporting at this time.
