### ISSUE TITLE
Support for ModelRead

### ISSUE THREAD

**Issue by Drehd** [LeonBlade/xnbcli#42]
C:\Users\H510\Downloads\xnbcli-windows-x64>xnbcli.exe unpack ".\packed" ".\unpacked"
[INFO] Reading file "packed\TerrainMesh.xnb" ...
[INFO] XNB file validated successfully!
[INFO] File has been successfully decompressed!
[ERROR] Filename: packed\TerrainMesh.xnb
XnbError: Non-implemented type found, cannot resolve type "Microsoft.Xna.Framework.Content.ModelReader", "Microsoft.Xna.Framework.Content.ModelReader, Microsoft.Xna.Framework.Graphics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553".
    at simplifyType (C:\snapshot\xnbcli\app\Xnb\TypeReader.js:0:0)
    at Xnb.load (C:\snapshot\xnbcli\app\Xnb\index.js:0:0)
    at processUnpack (C:\snapshot\xnbcli\xnbcli.js:0:0)
    at Walker.walker.on (C:\snapshot\xnbcli\xnbcli.js:0:0)
    at Walker.emit (events.js:198:13)
    at Object.emitSingleEvents [as emitNodeType] (C:\snapshot\xnbcli\node_modules\walk\lib\node-type-emitter.js:58:13)
    at Walker._wLstatHandler (C:\snapshot\xnbcli\node_modules\walk\lib\walk.js:88:19)
    at C:\snapshot\xnbcli\node_modules\walk\lib\walk.js:106:12
    at FSReqWrap.oncomplete (fs.js:154:5)

Success 0
Fail 1

C:\Users\H510\Downloads\xnbcli-windows-x64>echo Press enter to continue
Press enter to continue

C:\Users\H510\Downloads\xnbcli-windows-x64>pause
Press any key to continue . . .

**Comment by LeonBlade** [comment]
Related to #13
