### ISSUE TITLE
Error after running unpack

### ISSUE THREAD

**Issue by SashaTrincher** [LeonBlade/xnbcli#55]
XnbError: Non-implemented type found, cannot resolve type "StardewValley.GameData.Weapons.WeaponData", "StardewValley.GameData.Weapons.WeaponData, StardewValley.GameData, Version=1.6.4.24110, Culture=neutral, PublicKeyToken=null".
    at simplifyType (C:\snapshot\xnbcli\app\Xnb\TypeReader.js:0:0)
    at Array.map (<anonymous>)
    at simplifyType (C:\snapshot\xnbcli\app\Xnb\TypeReader.js:0:0)
    at Xnb.load (C:\snapshot\xnbcli\app\Xnb\index.js:0:0)
    at processUnpack (C:\snapshot\xnbcli\xnbcli.js:0:0)
    at Walker.walker.on (C:\snapshot\xnbcli\xnbcli.js:0:0)
    at Walker.emit (events.js:198:13)
    at Object.emitSingleEvents [as emitNodeType] (C:\snapshot\xnbcli\node_modules\walk\lib\node-type-emitter.js:58:13)
    at Walker._wLstatHandler (C:\snapshot\xnbcli\node_modules\walk\lib\walk.js:88:19)
    at C:\snapshot\xnbcli\node_modules\walk\lib\walk.js:106:12

**Comment by LeonBlade** [comment]
Unfortunately, there is not support for these data types that require reflection at the moment.

**Comment by SashaTrincher** [comment]
Are you planning to add that feature later on?

**Comment by LeonBlade** [comment]
It's unlikely that I will be supporting these advanced types due to the nature of how they must be implemented. For now, I will be closing this issue. Thank you.
