### ISSUE TITLE
Does not have "content" error when trying to pack?

### ISSUE THREAD

**Issue by fyrewrks** [LeonBlade/xnbcli#56]
I am getting this error when trying to pack files
[ERROR] Filename: unpacked\NPCNames.json
XnbError: unpacked\NPCNames.json does not have "content".
    at resolveImports (C:\snapshot\xnbcli\app\Porter.js:0:0)
    at processPack (C:\snapshot\xnbcli\xnbcli.js:0:0)
    at Walker.walker.on (C:\snapshot\xnbcli\xnbcli.js:0:0)
    at Walker.emit (events.js:198:13)
    at Object.emitSingleEvents [as emitNodeType] (C:\snapshot\xnbcli\node_modules\walk\lib\node-type-emitter.js:58:13)
    at Walker._wLstatHandler (C:\snapshot\xnbcli\node_modules\walk\lib\walk.js:88:19)
    at C:\snapshot\xnbcli\node_modules\walk\lib\walk.js:106:12
    at FSReqWrap.oncomplete (fs.js:154:5)
Am I missing something?

**Comment by donedonedone278** [comment]
I was having the same question but I figured it out: I wasn't thinking very hard and thought that I could re-pack files unpacked with stardewxnbhack. The reality is that the only files you can re-pack with xnbcli are those that were unpacked with xnbcli.
